# Applied only to terminals launched by the RIG i3 config.
font_family DejaVu Sans Mono
font_size 10.5
background #10131d
foreground #e4e8f1
background_opacity 0.87
background_blur 0
window_padding_width 14
cursor #23dcc8
cursor_shape beam
enable_audio_bell no
confirm_os_window_close -1
selection_background #ff365f
selection_foreground #ffffff
color0 #181d2c
color1 #ff365f
color2 #23dcc8
color3 #f4bd6a
color4 #778cff
color5 #b589ef
color6 #46cadd
color7 #e4e8f1
color8 #6d7792
color9 #ff6582
color10 #72efd7
color11 #ffdb8d
color12 #a4b2ff
color13 #d4b4ff
color14 #9ae4ef
color15 #ffffff
